<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Organization;

class OrganizationSeeder extends Seeder
{
    public function run(): void
    {
        $data = [

            [
                'name' => 'Anantara Dhigu',
                'company' => 'Anantara Dhigu Enterprises',
                'company_contact' => 'Dandre Stracke DDS',
                'tin_no' => 'TIN00001',
                'email' => 'anantara.dhigu@resorts.mv',
                'phone' => '74256904',
                'is_active' => false,
                'subscription_status' => 'active',
                'notes' => 'Way be especially night property.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Baros Maldives',
                'company' => 'Baros Maldives Enterprises',
                'company_contact' => 'Chester Greenfelder',
                'tin_no' => 'TIN00002',
                'email' => 'baros.maldives@resorts.mv',
                'phone' => '77744747',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Air necessary environmental clearly woman artist.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Coco Bodu Hithi',
                'company' => 'Coco Bodu Hithi Hospitality',
                'company_contact' => 'Ms. Itzel Kub',
                'tin_no' => 'TIN00003',
                'email' => 'coco.bodu.hithi@resorts.mv',
                'phone' => '73354852',
                'is_active' => false,
                'subscription_status' => 'cancelled',
                'notes' => 'So myself why task recently attorney town.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Dusit Thani',
                'company' => 'Dusit Thani Holdings',
                'company_contact' => 'Sheila Larkin',
                'tin_no' => 'TIN00004',
                'email' => 'dusit.thani@resorts.mv',
                'phone' => '75562845',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Anything fine audience night run.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Ellaidhoo Maldives',
                'company' => 'Ellaidhoo Maldives Hospitality',
                'company_contact' => 'Otis Krajcik',
                'tin_no' => 'TIN00005',
                'email' => 'ellaidhoo.maldives@resorts.mv',
                'phone' => '73663855',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Red expect less report painting fish treatment.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Fushifaru Maldives',
                'company' => 'Fushifaru Maldives Holdings',
                'company_contact' => 'Stanley Gislason PhD',
                'tin_no' => 'TIN00006',
                'email' => 'fushifaru.maldives@resorts.mv',
                'phone' => '73551078',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Hotel new provide argue surface set.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Gili Lankanfushi',
                'company' => 'Gili Lankanfushi Enterprises',
                'company_contact' => 'Darren Nader Sr.',
                'tin_no' => 'TIN00007',
                'email' => 'gili.lankanfushi@resorts.mv',
                'phone' => '77389404',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Affect think great behavior.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Hurawalhi Island',
                'company' => 'Hurawalhi Island Island Group',
                'company_contact' => 'Maureen Schultz',
                'tin_no' => 'TIN00008',
                'email' => 'hurawalhi.island@resorts.mv',
                'phone' => '73521354',
                'is_active' => false,
                'subscription_status' => 'suspended',
                'notes' => 'Ability property health dog kid from.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Innahura Maldives',
                'company' => 'Innahura Maldives Enterprises',
                'company_contact' => 'Jillian Schuppe',
                'tin_no' => 'TIN00009',
                'email' => 'innahura.maldives@resorts.mv',
                'phone' => '77140923',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Record improve year indeed cover single against identify.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'JA Manafaru',
                'company' => 'JA Manafaru Group Pvt Ltd',
                'company_contact' => 'Miss Era Kutch',
                'tin_no' => 'TIN00010',
                'email' => 'ja.manafaru@resorts.mv',
                'phone' => '76653802',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Remember hand talk resource.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Kandolhu Maldives',
                'company' => 'Kandolhu Maldives Hospitality',
                'company_contact' => 'Lucious Abernathy',
                'tin_no' => 'TIN00011',
                'email' => 'kandolhu.maldives@resorts.mv',
                'phone' => '70377007',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Reveal federal find home do keep.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'LUX* South Ari',
                'company' => 'LUX* South Ari Group Pvt Ltd',
                'company_contact' => 'Loyce Lubowitz',
                'tin_no' => 'TIN00012',
                'email' => 'lux.south.ari@resorts.mv',
                'phone' => '76066574',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Early that sign want east.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Meeru Island',
                'company' => 'Meeru Island Hospitality',
                'company_contact' => 'Paula Wolf',
                'tin_no' => 'TIN00013',
                'email' => 'meeru.island@resorts.mv',
                'phone' => '79192210',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Notice take baby.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Naladhu Private Island',
                'company' => 'Naladhu Private Island Holdings',
                'company_contact' => 'Stanley Bailey',
                'tin_no' => 'TIN00014',
                'email' => 'naladhu.private.island@resorts.mv',
                'phone' => '75541186',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Poor artist suddenly practice various.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Ozen Reserve Bolifushi',
                'company' => 'Ozen Reserve Bolifushi Enterprises',
                'company_contact' => 'Jena Batz',
                'tin_no' => 'TIN00015',
                'email' => 'ozen.reserve.bolifushi@resorts.mv',
                'phone' => '70404991',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Field travel see man member.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Park Hyatt Hadahaa',
                'company' => 'Park Hyatt Hadahaa Enterprises',
                'company_contact' => 'Shany Emard',
                'tin_no' => 'TIN00016',
                'email' => 'park.hyatt.hadahaa@resorts.mv',
                'phone' => '70743129',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Finish nearly fall.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Reethi Faru',
                'company' => 'Reethi Faru Island Group',
                'company_contact' => 'Mr. Kurtis Kertzmann DDS',
                'tin_no' => 'TIN00017',
                'email' => 'reethi.faru@resorts.mv',
                'phone' => '71043308',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Million nothing source economy even.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Soneva Jani',
                'company' => 'Soneva Jani Hospitality',
                'company_contact' => 'Brent Gleason',
                'tin_no' => 'TIN00018',
                'email' => 'soneva.jani@resorts.mv',
                'phone' => '72911970',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Ground win since during manage discussion.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Taj Exotica',
                'company' => 'Taj Exotica Enterprises',
                'company_contact' => 'Gretchen Lockman',
                'tin_no' => 'TIN00019',
                'email' => 'taj.exotica@resorts.mv',
                'phone' => '75225525',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Reflect pressure certain himself.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Vakkaru Maldives',
                'company' => 'Vakkaru Maldives Holdings',
                'company_contact' => 'Dovie Jones',
                'tin_no' => 'TIN00020',
                'email' => 'vakkaru.maldives@resorts.mv',
                'phone' => '75395154',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Goal score bad arm single product stock.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'W Maldives',
                'company' => 'W Maldives Island Group',
                'company_contact' => 'Kristian Rippin',
                'tin_no' => 'TIN00021',
                'email' => 'w.maldives@resorts.mv',
                'phone' => '72956912',
                'is_active' => false,
                'subscription_status' => 'suspended',
                'notes' => 'Sport challenge paper major.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'You & Me Maldives',
                'company' => 'You & Me Maldives Group Pvt Ltd',
                'company_contact' => 'Mr. Jeramy Little III',
                'tin_no' => 'TIN00022',
                'email' => 'you.me.maldives@resorts.mv',
                'phone' => '78407700',
                'is_active' => false,
                'subscription_status' => 'cancelled',
                'notes' => 'Sell specific position now.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Zitahli Resorts',
                'company' => 'Zitahli Resorts Hospitality',
                'company_contact' => 'Pietro Hodkiewicz',
                'tin_no' => 'TIN00023',
                'email' => 'zitahli.resorts@resorts.mv',
                'phone' => '73522881',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Relationship coach director adult recent nor commercial.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Ayada Maldives',
                'company' => 'Ayada Maldives Hospitality',
                'company_contact' => 'Ms. Elisha Kunde',
                'tin_no' => 'TIN00024',
                'email' => 'ayada.maldives@resorts.mv',
                'phone' => '75487121',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Second six rock country.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Constance Moofushi',
                'company' => 'Constance Moofushi Enterprises',
                'company_contact' => 'Dr. Rickey Brakus',
                'tin_no' => 'TIN00025',
                'email' => 'constance.moofushi@resorts.mv',
                'phone' => '72441898',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Cost reflect forget less.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Centara Ras Fushi',
                'company' => 'Centara Ras Fushi Hospitality',
                'company_contact' => 'Mrs. Fanny Jones',
                'tin_no' => 'TIN00026',
                'email' => 'centara.ras.fushi@resorts.mv',
                'phone' => '70795095',
                'is_active' => false,
                'subscription_status' => 'active',
                'notes' => 'Determine discuss until how marriage hard sport.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Sun Siyam Iru Fushi',
                'company' => 'Sun Siyam Iru Fushi Holdings',
                'company_contact' => 'Michel Hammes',
                'tin_no' => 'TIN00027',
                'email' => 'sun.siyam.iru.fushi@resorts.mv',
                'phone' => '79491410',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Garden left increase rather.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'The Standard Huruvalhi',
                'company' => 'The Standard Huruvalhi Group Pvt Ltd',
                'company_contact' => 'Dino Botsford',
                'tin_no' => 'TIN00028',
                'email' => 'the.standard.huruvalhi@resorts.mv',
                'phone' => '73158731',
                'is_active' => false,
                'subscription_status' => 'trial',
                'notes' => 'Decide say during do network short trial admit.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Kudadoo Maldives',
                'company' => 'Kudadoo Maldives Hospitality',
                'company_contact' => 'Ms. Chloe Yundt V',
                'tin_no' => 'TIN00029',
                'email' => 'kudadoo.maldives@resorts.mv',
                'phone' => '77916173',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Under plant medical.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Raffles Maldives',
                'company' => 'Raffles Maldives Holdings',
                'company_contact' => 'Easton Mante',
                'tin_no' => 'TIN00030',
                'email' => 'raffles.maldives@resorts.mv',
                'phone' => '79603867',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Possible knowledge nice agree would.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Hideaway Beach',
                'company' => 'Hideaway Beach Island Group',
                'company_contact' => 'Jocelyn Beer',
                'tin_no' => 'TIN00031',
                'email' => 'hideaway.beach@resorts.mv',
                'phone' => '73473509',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Position improve significant give out.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Robinson Club',
                'company' => 'Robinson Club Island Group',
                'company_contact' => 'Prof. Green Thiel',
                'tin_no' => 'TIN00032',
                'email' => 'robinson.club@resorts.mv',
                'phone' => '71532063',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Find possible stay.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Emerald Maldives',
                'company' => 'Emerald Maldives Hospitality',
                'company_contact' => 'Darby Kirlin',
                'tin_no' => 'TIN00033',
                'email' => 'emerald.maldives@resorts.mv',
                'phone' => '78318934',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Animal although military catch certainly.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Pullman Maldives',
                'company' => 'Pullman Maldives Holdings',
                'company_contact' => 'Kavon Ernser',
                'tin_no' => 'TIN00034',
                'email' => 'pullman.maldives@resorts.mv',
                'phone' => '72740160',
                'is_active' => false,
                'subscription_status' => 'suspended',
                'notes' => 'Operation say nation night of specific.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Amilla Fushi',
                'company' => 'Amilla Fushi Holdings',
                'company_contact' => 'Jerel Zieme',
                'tin_no' => 'TIN00035',
                'email' => 'amilla.fushi@resorts.mv',
                'phone' => '76413005',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Note color student despite alone.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Four Seasons Landaa',
                'company' => 'Four Seasons Landaa Hospitality',
                'company_contact' => 'Antwon Muller',
                'tin_no' => 'TIN00036',
                'email' => 'four.seasons.landaa@resorts.mv',
                'phone' => '76317672',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Modern talk medical include might.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Club Med Kani',
                'company' => 'Club Med Kani Hospitality',
                'company_contact' => 'Destinee McLaughlin',
                'tin_no' => 'TIN00037',
                'email' => 'club.med.kani@resorts.mv',
                'phone' => '75408735',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Discover strong poor.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Banyan Tree Vabbinfaru',
                'company' => 'Banyan Tree Vabbinfaru Hospitality',
                'company_contact' => 'Gianni Davis',
                'tin_no' => 'TIN00038',
                'email' => 'banyan.tree.vabbinfaru@resorts.mv',
                'phone' => '74289234',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'You certainly impact whom suddenly.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'OBLU Helengeli',
                'company' => 'OBLU Helengeli Enterprises',
                'company_contact' => 'Ms. Camylle Corkery',
                'tin_no' => 'TIN00039',
                'email' => 'oblu.helengeli@resorts.mv',
                'phone' => '71540862',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Finish operation car recognize eye keep.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'VARU by Atmosphere',
                'company' => 'VARU by Atmosphere Holdings',
                'company_contact' => 'Delta Heller',
                'tin_no' => 'TIN00040',
                'email' => 'varu.by.atmosphere@resorts.mv',
                'phone' => '77919936',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Test I now main activity social traditional option.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Hard Rock Hotel',
                'company' => 'Hard Rock Hotel Group Pvt Ltd',
                'company_contact' => 'Mr. Gabriel Lind I',
                'tin_no' => 'TIN00041',
                'email' => 'hard.rock.hotel@resorts.mv',
                'phone' => '71313110',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Hold form teach her.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Kuramathi Maldives',
                'company' => 'Kuramathi Maldives Holdings',
                'company_contact' => 'Skye Waelchi',
                'tin_no' => 'TIN00042',
                'email' => 'kuramathi.maldives@resorts.mv',
                'phone' => '73449463',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Responsibility choice value million after body.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Milaidhoo Island',
                'company' => 'Milaidhoo Island Hospitality',
                'company_contact' => 'Cordia Daniel',
                'tin_no' => 'TIN00043',
                'email' => 'milaidhoo.island@resorts.mv',
                'phone' => '76112286',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Single thousand leader couple keep.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Niyama Private Islands',
                'company' => 'Niyama Private Islands Enterprises',
                'company_contact' => 'Mr. Lane Pfeffer Jr.',
                'tin_no' => 'TIN00044',
                'email' => 'niyama.private.islands@resorts.mv',
                'phone' => '71661172',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Prove organization middle author start prepare.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Riu Palace Maldives',
                'company' => 'Riu Palace Maldives Holdings',
                'company_contact' => 'Mrs. Hildegard Brekke',
                'tin_no' => 'TIN00045',
                'email' => 'riu.palace.maldives@resorts.mv',
                'phone' => '74460514',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Hear feel drug magazine Mrs nice by.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'The St. Regis Vommuli',
                'company' => 'The St. Regis Vommuli Group Pvt Ltd',
                'company_contact' => 'Onie Bins',
                'tin_no' => 'TIN00046',
                'email' => 'the.st.regis.vommuli@resorts.mv',
                'phone' => '76007552',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'College good speak doctor hear.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Veligandu Island',
                'company' => 'Veligandu Island Enterprises',
                'company_contact' => 'Bernice Moen',
                'tin_no' => 'TIN00047',
                'email' => 'veligandu.island@resorts.mv',
                'phone' => '79015010',
                'is_active' => false,
                'subscription_status' => 'cancelled',
                'notes' => 'Him direction type different production low.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Vilamendhoo Island',
                'company' => 'Vilamendhoo Island Hospitality',
                'company_contact' => 'Prof. Freddy Luettgen PhD',
                'tin_no' => 'TIN00048',
                'email' => 'vilamendhoo.island@resorts.mv',
                'phone' => '74668584',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Operation talk party improve few better.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Kagi Maldives',
                'company' => 'Kagi Maldives Enterprises',
                'company_contact' => 'Hank Luettgen',
                'tin_no' => 'TIN00049',
                'email' => 'kagi.maldives@resorts.mv',
                'phone' => '71863379',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Board deep another live close.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'COMO Maalifushi',
                'company' => 'COMO Maalifushi Holdings',
                'company_contact' => 'Mr. Ezra Altenwerth',
                'tin_no' => 'TIN00050',
                'email' => 'como.maalifushi@resorts.mv',
                'phone' => '75339551',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Possible walk condition involve hold power.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Anantara Dhigu',
                'company' => 'Anantara Dhigu Hospitality',
                'company_contact' => 'Dr. Morton Fisher',
                'tin_no' => 'TIN00001',
                'email' => 'anantara.dhigu@resorts.mv',
                'phone' => '77780835',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Whether money threat truth.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Baros Maldives',
                'company' => 'Baros Maldives Holdings',
                'company_contact' => 'Dr. Jennings Bartell',
                'tin_no' => 'TIN00002',
                'email' => 'baros.maldives@resorts.mv',
                'phone' => '75035655',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Only point human long city easy.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Coco Bodu Hithi',
                'company' => 'Coco Bodu Hithi Island Group',
                'company_contact' => 'Dr. Timmy Wisozk',
                'tin_no' => 'TIN00003',
                'email' => 'coco.bodu.hithi@resorts.mv',
                'phone' => '75182052',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Scientist the administration building whole.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Dusit Thani',
                'company' => 'Dusit Thani Hospitality',
                'company_contact' => 'Alexandre Bogisich DDS',
                'tin_no' => 'TIN00004',
                'email' => 'dusit.thani@resorts.mv',
                'phone' => '71342424',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Expect prove health onto.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Ellaidhoo Maldives',
                'company' => 'Ellaidhoo Maldives Hospitality',
                'company_contact' => 'Judy Hoeger',
                'tin_no' => 'TIN00005',
                'email' => 'ellaidhoo.maldives@resorts.mv',
                'phone' => '71961510',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Attention sign pressure.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Fushifaru Maldives',
                'company' => 'Fushifaru Maldives Hospitality',
                'company_contact' => 'Eveline Hirthe',
                'tin_no' => 'TIN00006',
                'email' => 'fushifaru.maldives@resorts.mv',
                'phone' => '74434038',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Artist know alone others glass suffer.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Gili Lankanfushi',
                'company' => 'Gili Lankanfushi Holdings',
                'company_contact' => 'Susanna Metz',
                'tin_no' => 'TIN00007',
                'email' => 'gili.lankanfushi@resorts.mv',
                'phone' => '71087168',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'None bill mean agree quickly.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Hurawalhi Island',
                'company' => 'Hurawalhi Island Island Group',
                'company_contact' => 'Prof. Ervin Lang DDS',
                'tin_no' => 'TIN00008',
                'email' => 'hurawalhi.island@resorts.mv',
                'phone' => '73079135',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Fact fear skin modern.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Innahura Maldives',
                'company' => 'Innahura Maldives Group Pvt Ltd',
                'company_contact' => 'Josefina Zulauf',
                'tin_no' => 'TIN00009',
                'email' => 'innahura.maldives@resorts.mv',
                'phone' => '76860604',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Seem perform appear kind.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'JA Manafaru',
                'company' => 'JA Manafaru Island Group',
                'company_contact' => 'Douglas McLaughlin',
                'tin_no' => 'TIN00010',
                'email' => 'ja.manafaru@resorts.mv',
                'phone' => '77967715',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Security decide never lead different.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Kandolhu Maldives',
                'company' => 'Kandolhu Maldives Holdings',
                'company_contact' => 'Mrs. Camilla Zemlak',
                'tin_no' => 'TIN00011',
                'email' => 'kandolhu.maldives@resorts.mv',
                'phone' => '78424251',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Teach responsibility question scene.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'LUX* South Ari',
                'company' => 'LUX* South Ari Hospitality',
                'company_contact' => 'Miss Kathleen Gutkowski Jr.',
                'tin_no' => 'TIN00012',
                'email' => 'lux.south.ari@resorts.mv',
                'phone' => '70069791',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Him middle west people cut Congress eight summer.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Meeru Island',
                'company' => 'Meeru Island Hospitality',
                'company_contact' => 'Prof. Hulda Hand',
                'tin_no' => 'TIN00013',
                'email' => 'meeru.island@resorts.mv',
                'phone' => '77695928',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Still laugh natural course husband.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Naladhu Private Island',
                'company' => 'Naladhu Private Island Hospitality',
                'company_contact' => 'Dr. Jamir Trantow',
                'tin_no' => 'TIN00014',
                'email' => 'naladhu.private.island@resorts.mv',
                'phone' => '76426977',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Page hundred fast speech easy street.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Ozen Reserve Bolifushi',
                'company' => 'Ozen Reserve Bolifushi Group Pvt Ltd',
                'company_contact' => 'Norwood Lockman',
                'tin_no' => 'TIN00015',
                'email' => 'ozen.reserve.bolifushi@resorts.mv',
                'phone' => '74318902',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Man American season exist find.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Park Hyatt Hadahaa',
                'company' => 'Park Hyatt Hadahaa Enterprises',
                'company_contact' => 'Mayra Weber',
                'tin_no' => 'TIN00016',
                'email' => 'park.hyatt.hadahaa@resorts.mv',
                'phone' => '76791760',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Society pull nature first never public stand.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Reethi Faru',
                'company' => 'Reethi Faru Group Pvt Ltd',
                'company_contact' => 'Amir Sporer MD',
                'tin_no' => 'TIN00017',
                'email' => 'reethi.faru@resorts.mv',
                'phone' => '76906130',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Move meeting listen find see.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Soneva Jani',
                'company' => 'Soneva Jani Hospitality',
                'company_contact' => 'Arnaldo Kreiger',
                'tin_no' => 'TIN00018',
                'email' => 'soneva.jani@resorts.mv',
                'phone' => '76688886',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Man son would above similar somebody.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Taj Exotica',
                'company' => 'Taj Exotica Enterprises',
                'company_contact' => 'Eula Gusikowski IV',
                'tin_no' => 'TIN00019',
                'email' => 'taj.exotica@resorts.mv',
                'phone' => '79718231',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Pattern budget throw.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Vakkaru Maldives',
                'company' => 'Vakkaru Maldives Group Pvt Ltd',
                'company_contact' => 'Flossie Schmeler',
                'tin_no' => 'TIN00020',
                'email' => 'vakkaru.maldives@resorts.mv',
                'phone' => '73458163',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Reduce quality old arm.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'W Maldives',
                'company' => 'W Maldives Island Group',
                'company_contact' => 'Dr. Brooks Wehner',
                'tin_no' => 'TIN00021',
                'email' => 'w.maldives@resorts.mv',
                'phone' => '73568502',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Drive though sort prove.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'You & Me Maldives',
                'company' => 'You & Me Maldives Hospitality',
                'company_contact' => 'Brisa Mosciski',
                'tin_no' => 'TIN00022',
                'email' => 'you.me.maldives@resorts.mv',
                'phone' => '79500703',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Relationship result adult recognize police.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Zitahli Resorts',
                'company' => 'Zitahli Resorts Hospitality',
                'company_contact' => 'Hilbert McLaughlin V',
                'tin_no' => 'TIN00023',
                'email' => 'zitahli.resorts@resorts.mv',
                'phone' => '78111271',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'His option finish military us group.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Ayada Maldives',
                'company' => 'Ayada Maldives Group Pvt Ltd',
                'company_contact' => 'Lincoln Reilly',
                'tin_no' => 'TIN00024',
                'email' => 'ayada.maldives@resorts.mv',
                'phone' => '70095414',
                'is_active' => false,
                'subscription_status' => 'suspended',
                'notes' => 'Sort necessary economy manage speak say.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Constance Moofushi',
                'company' => 'Constance Moofushi Enterprises',
                'company_contact' => 'Prof. Chadd Maggio',
                'tin_no' => 'TIN00025',
                'email' => 'constance.moofushi@resorts.mv',
                'phone' => '79658603',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Himself assume easy state.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Centara Ras Fushi',
                'company' => 'Centara Ras Fushi Group Pvt Ltd',
                'company_contact' => 'Dr. Howell Hartmann',
                'tin_no' => 'TIN00026',
                'email' => 'centara.ras.fushi@resorts.mv',
                'phone' => '73873626',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Threat challenge fast head most represent audience.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Sun Siyam Iru Fushi',
                'company' => 'Sun Siyam Iru Fushi Hospitality',
                'company_contact' => 'Eva Heaney',
                'tin_no' => 'TIN00027',
                'email' => 'sun.siyam.iru.fushi@resorts.mv',
                'phone' => '75781655',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Sense child us another growth.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'The Standard Huruvalhi',
                'company' => 'The Standard Huruvalhi Enterprises',
                'company_contact' => 'Prof. Annabel Bruen I',
                'tin_no' => 'TIN00028',
                'email' => 'the.standard.huruvalhi@resorts.mv',
                'phone' => '76196860',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Hot establish service method might effort.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Kudadoo Maldives',
                'company' => 'Kudadoo Maldives Island Group',
                'company_contact' => 'Odie Hane Jr.',
                'tin_no' => 'TIN00029',
                'email' => 'kudadoo.maldives@resorts.mv',
                'phone' => '70157210',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'More stuff nor remember student interview.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Raffles Maldives',
                'company' => 'Raffles Maldives Enterprises',
                'company_contact' => 'Doug Ullrich',
                'tin_no' => 'TIN00030',
                'email' => 'raffles.maldives@resorts.mv',
                'phone' => '73353401',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Whatever drive station.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Hideaway Beach',
                'company' => 'Hideaway Beach Group Pvt Ltd',
                'company_contact' => 'Prof. Evert Waelchi IV',
                'tin_no' => 'TIN00031',
                'email' => 'hideaway.beach@resorts.mv',
                'phone' => '79804769',
                'is_active' => false,
                'subscription_status' => 'active',
                'notes' => 'Ball toward worker because answer once thus food.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Robinson Club',
                'company' => 'Robinson Club Holdings',
                'company_contact' => 'Adonis Hirthe',
                'tin_no' => 'TIN00032',
                'email' => 'robinson.club@resorts.mv',
                'phone' => '76876074',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Wife pressure up leader.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Emerald Maldives',
                'company' => 'Emerald Maldives Group Pvt Ltd',
                'company_contact' => 'Mrs. Sydnee Lubowitz',
                'tin_no' => 'TIN00033',
                'email' => 'emerald.maldives@resorts.mv',
                'phone' => '72682926',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Especially agree meet no year few.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Pullman Maldives',
                'company' => 'Pullman Maldives Enterprises',
                'company_contact' => 'Beatrice Macejkovic I',
                'tin_no' => 'TIN00034',
                'email' => 'pullman.maldives@resorts.mv',
                'phone' => '78899986',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Include expect past street trade single hold.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Amilla Fushi',
                'company' => 'Amilla Fushi Holdings',
                'company_contact' => 'Christophe Blanda',
                'tin_no' => 'TIN00035',
                'email' => 'amilla.fushi@resorts.mv',
                'phone' => '79270262',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Free several challenge walk not building explain response.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Four Seasons Landaa',
                'company' => 'Four Seasons Landaa Holdings',
                'company_contact' => 'Ms. Ashley Trantow I',
                'tin_no' => 'TIN00036',
                'email' => 'four.seasons.landaa@resorts.mv',
                'phone' => '77764311',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Case chair his baby career whole cup need.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Club Med Kani',
                'company' => 'Club Med Kani Island Group',
                'company_contact' => 'Wellington Gleichner',
                'tin_no' => 'TIN00037',
                'email' => 'club.med.kani@resorts.mv',
                'phone' => '75717120',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Upon great improve think foreign past capital agency.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Banyan Tree Vabbinfaru',
                'company' => 'Banyan Tree Vabbinfaru Hospitality',
                'company_contact' => 'Milan Pouros',
                'tin_no' => 'TIN00038',
                'email' => 'banyan.tree.vabbinfaru@resorts.mv',
                'phone' => '73864299',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Performance he stage dark else scientist dream south.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'OBLU Helengeli',
                'company' => 'OBLU Helengeli Hospitality',
                'company_contact' => 'Raquel Wiegand V',
                'tin_no' => 'TIN00039',
                'email' => 'oblu.helengeli@resorts.mv',
                'phone' => '77240658',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Car benefit thank themselves investment final technology.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'VARU by Atmosphere',
                'company' => 'VARU by Atmosphere Holdings',
                'company_contact' => 'Dane Grimes PhD',
                'tin_no' => 'TIN00040',
                'email' => 'varu.by.atmosphere@resorts.mv',
                'phone' => '73531602',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Teach they majority hold doctor course development.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Hard Rock Hotel',
                'company' => 'Hard Rock Hotel Island Group',
                'company_contact' => 'Ms. Emily Von V',
                'tin_no' => 'TIN00041',
                'email' => 'hard.rock.hotel@resorts.mv',
                'phone' => '73971090',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Hit finally medical less number them.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Kuramathi Maldives',
                'company' => 'Kuramathi Maldives Holdings',
                'company_contact' => 'Victor Welch',
                'tin_no' => 'TIN00042',
                'email' => 'kuramathi.maldives@resorts.mv',
                'phone' => '76055245',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Draw remain fall order federal write.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Milaidhoo Island',
                'company' => 'Milaidhoo Island Enterprises',
                'company_contact' => 'Prof. Sigmund Howe MD',
                'tin_no' => 'TIN00043',
                'email' => 'milaidhoo.island@resorts.mv',
                'phone' => '77341711',
                'is_active' => false,
                'subscription_status' => 'trial',
                'notes' => 'East since like notice.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Niyama Private Islands',
                'company' => 'Niyama Private Islands Enterprises',
                'company_contact' => 'Evan Reichel',
                'tin_no' => 'TIN00044',
                'email' => 'niyama.private.islands@resorts.mv',
                'phone' => '72447276',
                'is_active' => true,
                'subscription_status' => 'cancelled',
                'notes' => 'Offer deep century factor.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Riu Palace Maldives',
                'company' => 'Riu Palace Maldives Hospitality',
                'company_contact' => 'Mr. Russ Heidenreich',
                'tin_no' => 'TIN00045',
                'email' => 'riu.palace.maldives@resorts.mv',
                'phone' => '74053757',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Form continue media miss.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'The St. Regis Vommuli',
                'company' => 'The St. Regis Vommuli Holdings',
                'company_contact' => 'Dr. Darron Yost',
                'tin_no' => 'TIN00046',
                'email' => 'the.st.regis.vommuli@resorts.mv',
                'phone' => '75310625',
                'is_active' => false,
                'subscription_status' => 'trial',
                'notes' => 'Contain beyond former else collection.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Veligandu Island',
                'company' => 'Veligandu Island Island Group',
                'company_contact' => 'Queen Schiller',
                'tin_no' => 'TIN00047',
                'email' => 'veligandu.island@resorts.mv',
                'phone' => '74898030',
                'is_active' => true,
                'subscription_status' => 'trial',
                'notes' => 'Focus threat voice team.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Vilamendhoo Island',
                'company' => 'Vilamendhoo Island Group Pvt Ltd',
                'company_contact' => 'Dixie Pacocha',
                'tin_no' => 'TIN00048',
                'email' => 'vilamendhoo.island@resorts.mv',
                'phone' => '72120705',
                'is_active' => true,
                'subscription_status' => 'active',
                'notes' => 'Two feeling since show quite indeed.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'Kagi Maldives',
                'company' => 'Kagi Maldives Enterprises',
                'company_contact' => 'Dr. Jamar Price V',
                'tin_no' => 'TIN00049',
                'email' => 'kagi.maldives@resorts.mv',
                'phone' => '79761365',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Picture feel goal day your just attorney.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
            [
                'name' => 'COMO Maalifushi',
                'company' => 'COMO Maalifushi Hospitality',
                'company_contact' => 'Prof. Freda Gutkowski Sr.',
                'tin_no' => 'TIN00050',
                'email' => 'como.maalifushi@resorts.mv',
                'phone' => '71499183',
                'is_active' => true,
                'subscription_status' => 'suspended',
                'notes' => 'Many line measure personal another catch forget.',
                'created_at' => '2025-07-31 12:37:05',
                'updated_at' => '2025-07-31 12:37:05',
            ],
        ];

        foreach ($data as $item) {
            Organization::create($item);
        }
    }
}
